export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';

export const API_CALL_ERROR = 'API_CALL_ERROR';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';

export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
